### ISSUE TITLE
Fullscreen without virtual buttons

### ISSUE THREAD

**Issue by hitaloramon** [frontyard/cordova-plugin-exoplayer#10]
I'm not mistaken in the previous version had something to open in fullscreen.
Without the virtual buttons. Was that version removed?

Can you make the player open in fullscreen?

**Comment by frontyard** [comment]
@hitaloramon Are you talking about notification bar? That shouldn't have changed, player should start full screen. What device are you testing it on?
I will make sure I didn't break anything.

**Comment by hitaloramon** [comment]
They are the navigation bars, with the buttons back, start, recent
Tested on MotoG, but several are like that.

It has immersive function, I tried to modify here but I do not understand much of java, so I did not succeed.

Print: https://prnt.sc/f92u9o

**Comment by hitaloramon** [comment]
@frontyard  It would be here, just do not know how to do. I hope it helps:

https://developer.android.com/training/system-ui/navigation.html

I wish I could know java :) kkk

**Comment by frontyard** [comment]
@hitaloramon Please try latest version (2.2.0) and let me know if that solves your problem.
