### ISSUE TITLE
player controller does not view

### ISSUE THREAD

**Issue by mkalyon** [frontyard/cordova-plugin-exoplayer#12]
I use contoller params like that

controller: { 
        streamImage: 'http://aaa.jpg',
        streamTitle: 'my channel',
        streamDescription: '.........',
        hideProgress: false
    }
streamimage and titles are showing.
progress bar is not showing.
play,pause and others are not showing.

**Comment by hitaloramon** [comment]
To show a progress bar you need to remove a description

"Controller is composed of several pieces. To the left there is optional streamImage, followed by two lines, top and bottom. Top line is reserved for streamTitle, while bottom line can either be streamDescription or progress bar. If you provide streamDescription, progress bar will not be visible. Optionaly you can turn off progress bar by passing hideProgress: true if you don't want to show either."

**Comment by frontyard** [comment]
@mkalyon in addition to what @hitaloramon suggested if you want to show control buttons you need `controlIcons` inside controller. So if you're not gonna override the icons just put:
controlIcons: {}

**Comment by mkalyon** [comment]
Thanks @hitaloramon and @frontyard

**Comment by mkalyon** [comment]
@frontyard how to change controller  background color and  position?

**Comment by frontyard** [comment]
@mkalyon You can't do that just yet. This might be coming in future versions.

**Comment by mkalyon** [comment]
Thank you @frontyard.
Can you add font size, font color and etc.
