### ISSUE TITLE
Regain a player handle after page reloading

### ISSUE THREAD

**Issue by netmikey** [frontyard/cordova-plugin-exoplayer#13]
I'm using the exoplayer plugin in the `audioOnly: true` mode, so I don't show an exoplayer view. I control playback via API calls and get player feedback via the events, just as described in the README.

I have a situation where the player is running in the background and my application triggers an OAuth login. This involves redirecting between pages a couple of times and eventually leads back to my app. Now during this process, the exoplayer keeps playing in the background, which is a good thing as this gives a true "app-like" immersive feeling.

The issue however is that when the webview navigates back to my app after the OAuth redirects, the moment `deviceready` fires, I have no way of obtaining the running exoplayer's state. I noticed that when I `show()` a new exoplayer, the "old" one stops playing and gets replaced with the new one, which kind of "reconnects" my application to the exoplayer, but it would be way cooler if I could retrieve the player handle something like this (the `retrieve()` function is what I'm looking for):

    var existingPlayer = exoplayer.retrieve();
    if (existingPlayer != null) {
        // An exoplayer is running, now we can access its state...
        existingPlayer.getState(successCallback, errorCallback);
    } else {
        // No exoplayer currently running, create a new one...
        var player = exoplayer.init({ ... });
        player.show();
    }

Any chance we could get something like this?

**Comment by frontyard** [comment]
@netmikey It looks like you're losing original handle to the player when your app starts redirecting, and without closing the player it keeps playing. I've experimented with this before and found that I could play more then one stream at the same time like that (at least on devices I have). Android just muxes the two together (sometimes to a very amusing effect). So I'm not sure what you're asking is possible.

Is it possible to rework your app to hang on to that original handle somehow?

**Comment by netmikey** [comment]
Since it's impossible to hold on to a JavaScript Object across redirects, that would mean not redirecting at all. However, I'm afraid that's not possible cause it's just the way OAuth works...

If the player kept playing both streams at the same time it would be even worse for me, so I'm glad it actually doesn't seem to do this in my case.

**Disclaimer: I'm a total novice in Cordova Plugin development, so feel free to correct me in whatever follows ;-)**

I found this in the [cordova docs](https://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html#plugin-initialization-and-lifetime):

> One instance of a plugin object is created for the life of each WebView. 

So my idea was this: I cannot hold state across page loads in my part of the application. However, your plugin on the native android side (the Java part) should keep the same instance, even across my redirects, right? If that's the case, then both the calls before and after the redirection end up on the same cordova-plugin-exoplayer instance. So whenever you get the proposed `retrieve()` call on the Java side, you could simply check whether or not you have an exoplayer instance running, and if so, build the `player` instance in javascript, wire it up to the running exoplayer and return it in the javascript side to my application.

Does that make sense?

**Comment by frontyard** [comment]
@netmikey I think I got something. Will release new version soon.

**Comment by netmikey** [comment]
@frontyard Awesome, looking forward to this one! :)

**Comment by frontyard** [comment]
@netmikey Version 2.3.0 is available. Please check the [docs](https://github.com/frontyard/cordova-plugin-exoplayer) as some of the API has changed.

**Comment by netmikey** [comment]
Yes: I can confirm that > 2.3.0's API `ExoPlayer.getState(...)` enables me to reconnect my GUI after any redirect, great! 👍
