### ISSUE TITLE
Allow enable/disable of subtitles through player's controls

### ISSUE THREAD

**Issue by frontyard** [frontyard/cordova-plugin-exoplayer#15]
Requested by @hitaloramon.

It would be nice if subtitles could be turned on and off from player's control bar. This however has to support both touchscreen and keyboard (for TV remotes) and not affect existing functionality.

This new functionality could trigger new keyboard event and pass it to Cordova just like existing events.

**Comment by hitaloramon** [comment]
Yes, it would also be interesting with a control button.

**Comment by super94i** [comment]
Any update on this?

**Comment by naja7host** [comment]
Update?

**Comment by frontyard** [comment]
If anyone has time to work on this and submit a pull request that would be awesome, otherwise it's probably not gonna happen.
