### ISSUE TITLE
Chromecast Suport

### ISSUE THREAD

**Issue by hitaloramon** [frontyard/cordova-plugin-exoplayer#16]
@frontyard  

Could I add support for chromecast with Subtitle Submission?
I've been researching the subject and found this playlist:

`https://www.youtube.com/playlist?list=PLTK0VPsbaNGpAM-ni5fMJkPeQDpXo_UwK`

I think it might help. All the code from this video example is available here: 

`https://github.com/kunalbhatia/avp/`

I would like to be able to help more to make this player look better, but my knowledge in java is not very good lol.

Thanks for everything.

**Comment by frontyard** [comment]
@hitaloramon Chromecast support doesn't really have anything to do with ExoPlayer. While ExoPlayer allows you to stream videos localy, chromecast allows those streams to be played (or "casted") on compatible chromecast devices. There are several plugins for Cordova that are attempting to provide such functionality, but I haven't played with any of them.

**Comment by frontyard** [comment]
@hitaloramon Maybe this could help:
https://github.com/nbabanov/cordova-chromecast
https://github.com/videostream/cordova-chromecast
