### ISSUE TITLE
Media controls on notification bar

### ISSUE THREAD

**Issue by go2hyder** [frontyard/cordova-plugin-exoplayer#17]
Is there any way to add media player controls in notification bar for streaming audio?

**Comment by netmikey** [comment]
If this is being considered, please make it optional. We populate player controls and media info ourselves directly from our app using another cordova plugin.

**Comment by frontyard** [comment]
No this is not being considered as it falls outside the scope of ExoPlayer. I'm sure there are few Cordova plugins out there that perform this exact function.

**Comment by netmikey** [comment]
@go2hyder We use https://github.com/homerours/cordova-music-controls-plugin on android, which does exactly what we want.
