### ISSUE TITLE
Controller position, backgroud color, font-size

### ISSUE THREAD

**Issue by mkalyon** [frontyard/cordova-plugin-exoplayer#19]
Hi @frontyard,
Please add controller position, background color, font-size, progress bar color and etc. parameters.
Thank you

**Comment by frontyard** [comment]
There is some new development that might give you what you need which is using Cordova to do player controls vs controls built into this plugin. This would really be the ideal solution, if it works :-)

Check the latest code in 2.0.0 branch.
