### ISSUE TITLE
Player stops playing in background on some devices

### ISSUE THREAD

**Issue by netmikey** [frontyard/cordova-plugin-exoplayer#20]
We get reports from some users that when their device locks, or goes to sleep (in short: when the app enters the background), the music stops playing after a couple of minutes. As soon as they unlock their device and the app comes back on, it starts buffering and continues playing.

We get this mainly from Samsung users, in one concrete case it is a Samsung Galaxy S6 Edge+. We made sure the user has all energy saver options disabled and we even made him add the app into the battery optimisation whitelist, but nothing seems to help.

Do you have any experience with these kind of issues? Or any hint at what we might do to diagnose exactly _why_ exoplayer stops playing in the background on some devices?

**Comment by frontyard** [comment]
@netmikey Are you able to replicate this behavior yourself?
Is your app receiving `pause` event from Cordova when music stops? https://cordova.apache.org/docs/en/4.0.0/cordova/events/events.html

**Comment by netmikey** [comment]
Unfortunately, on my ZTE test phone with Android 6.0, I cannot replicate this behaviour.
From what I understand, the app gets the pause event when it enters the background, but the music keeps playing a couple of minutes (so definitely longer than the buffered data) _after_ the app has entered the background. The app doesn't do anything special yet when getting the pause event.

**Comment by frontyard** [comment]
It sounds like Android is pausing your app after a while. It is recommended to create apps that will run in the background as services, not sure if you're able to do that.

There seems to be few Cordova plugins you might take a look for inspiration (I haven't used any of them):
https://github.com/katzer/cordova-plugin-background-mode
https://github.com/MobileChromeApps/cordova-plugin-background-app

**Comment by netmikey** [comment]
Just wanted to give a quick feedback on this issue:

It looks like I managed to get rid of the aforementioned problem by just adding the `cordova-plugin-background-mode` and calling `cordova.plugins.backgroundMode.disableWebViewOptimizations();`.

While developing, I had an issue with putting the app into background mode, so I wanted to put out a test version of our app with other fixes where I wouldn't put the app into the background just yet. As it turned out, just adding the plugin and calling said method was enough to let our app keep playing in the background with `cordova-plugin-exoplayer`.

=> Problem solved! 👍

**Comment by frontyard** [comment]
@netmikey Wonderful! Good info.

BTW, is your app publicly available? I'd love to see what folks are doing with this plugin.

**Comment by netmikey** [comment]
Kind of: we have a beta version out right now: https://play.google.com/apps/testing/com.RauteMusik.RadioPlayer

BTW, while we're at it: the only real blocker left to us before we can go live with this new version is #21 - would be awesome if you could have a look! ;-)

**Comment by frontyard** [comment]
@netmikey Coming very soon :-)

**Comment by frontyard** [comment]
@netmikey Version 2.4.0 now requests audio focus and monitors it. Please let me know if it works/doesn't.
