### ISSUE TITLE
How to detect if player is null

### ISSUE THREAD

**Issue by ashokkumar88** [frontyard/cordova-plugin-exoplayer#22]
Hi,

If i am calling window.ExoPlayer.getState() after close() then app crashes. So how can i detect that the player is empty/null.

Thanks

**Comment by frontyard** [comment]
@ashokkumar88 Do you mind posting any errors you see in android log (adb logcat) related to the plugin? I haven't tested this particular scenario.

**Comment by frontyard** [comment]
You shouldn't be calling getState after close. Close will dispose of player which means you need to call show again to get the new instance which will respond to getState.
