### ISSUE TITLE
Add methods to control volume

### ISSUE THREAD

**Issue by scramatte** [frontyard/cordova-plugin-exoplayer#24]
It would be nice to add methods to control volume : up , down, mute

**Comment by frontyard** [comment]
Volume is controlled by android itself. Most devices either have hardware volume buttons or remote with volume keys. While it's technically possible to control volume it's not recommended.

**Comment by scramatte** [comment]
I've seen the following feature into VLC player.  It's quite cool to be able to control volume with gestures

**Comment by scramatte** [comment]
http://www.idownloadblog.com/2013/08/23/vlc-gestures/

**Comment by frontyard** [comment]
@scramatte Controlling system audio volume is not in scope for this plugin. Touch events are forwarded to your Cordova app and there is nothing preventing you from implementing audio volume control through another plugin like https://www.npmjs.com/package/cordova-plugin-android-utilities.
