### ISSUE TITLE
add methods to show/hide controls

### ISSUE THREAD

**Issue by scramatte** [frontyard/cordova-plugin-exoplayer#25]
It would be nice to add methods to be able to show/hide control on event raising.
For example touch anywhere should hide controls.

**Comment by frontyard** [comment]
The controls are currently shown on touch and stay on for 5 seconds.

Maybe we shouldn't be showing controls automatically but let the app decide when to show them?

**Comment by frontyard** [comment]
This has been added in recent versions.
