### ISSUE TITLE
How to show a loading image in player while buffering

### ISSUE THREAD

**Issue by ashokkumar88** [frontyard/cordova-plugin-exoplayer#27]
Hi,

While buffering how can i display a loading image in the player?

**Comment by frontyard** [comment]
You can't. It sounds like unnecessary complication 😄  Would it show only initially or every time player buffers? Would it show regardless of how much time the buffering is taking? This could potentially create a "twitching" effect where image is displayed for fraction of a second followed by video, which wouldn't really be good.

Maybe a spinner that would show while player is buffering would be more helpful?

**Comment by ashokkumar88** [comment]
Hi forntyard,

Thanks for your reply. Yes it will be a spinner which will show when the video buffers like in Youtube.

**Comment by ashokkumar88** [comment]
Hi frontyard,

Can u please let me know how to show the loader? Which Java file to edit to show the loader?

**Comment by frontyard** [comment]
Version 2.5.4 shows indeterminate progress bar at the top of the screen. You need to enable it with configuration setting.

Please let me know if that works for you.
