### ISSUE TITLE
The player get stuck in buffering state and the player not returning to the ready state

### ISSUE THREAD

**Issue by ashokkumar88** [frontyard/cordova-plugin-exoplayer#29]
Hi,

I streamed a remote mp3 file. When the player goes to buffer state it get stuck. It is not returning to the ready state after then. I have to stop the player and again restart.

**Comment by frontyard** [comment]
Hey @ashokkumar88, I would need more debug info to begin to understand what's going wrong there. Please run 'adb logcat' and also chrome://inspect your Cordova app.

**Comment by ashokkumar88** [comment]
The issue is resolved when update to the latest version of exoplayer. Thanks
