### ISSUE TITLE
forward and rewind plugin method

### ISSUE THREAD

**Issue by mkalyon** [frontyard/cordova-plugin-exoplayer#30]
Hi @frontyard,
Could you add forward and rewind plugin method?

**Comment by mkalyon** [comment]
I have solved using seekTo plugin method in javascript.

                var duration=0;
		var position=0;
		window.ExoPlayer.getState(function(data){
				var m=JSON.stringify(data);
				duration=parseInt(parser(m,'duration":"','"'));
				position=parseInt(parser(m,'position":"','"'));
				var time=position+60000;
				if (time > duration)
				{
					time=duration;
				}
				window.ExoPlayer.seekTo(time);
				window.ExoPlayer.showController();
		}, function(error){});

**Comment by frontyard** [comment]
👍
