### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by mkalyon** [frontyard/cordova-plugin-exoplayer#31]
Hi @frontyard,
Thank you for all supports.
I can not find donation way for you.
How can I donate?
Best Regards
mkalyon

**Comment by frontyard** [comment]
@mkalyon Thank! I added a button to the front page. Also here:
https://www.paypal.me/frontyard/

**Comment by mkalyon** [comment]
Thanks @frontyard 
Can you create donate button in paypal or can you add other methods.
Because We cannot use paypal in onur country.
If you add donate button, I will try to donate.

**Comment by frontyard** [comment]
@mkalyon I have updated that link. Thanks for your support!

**Comment by mkalyon** [comment]
Sorry @frontyard ,
I cannot donate using paypal in my country. But I will donate , my firiend donates to you for me.
I will write when donated.
Thanks

**Comment by frontyard** [comment]
@mkalyon Sorry about that. Paypal does accept credit cards as well. But in any case, don't worry about it. I'm happy to see support for this project.

**Comment by mkalyon** [comment]
Hi @frontyard
I have donated using my friend paypal account.
Thank you for all support.
