### ISSUE TITLE
Is it possible, changing video quality in HLS?

### ISSUE THREAD

**Issue by mkalyon** [frontyard/cordova-plugin-exoplayer#32]
We can change or select video quality in HLS?
Can we set maximum bitrate in plugin?
Thanks

**Comment by frontyard** [comment]
You can't change quality of the video without re-encoding it. This can be done on a server with something like ffmpeg, wowza or adobe media server. But definitely not on a tiny android media player :-)

What is possible though is adaptive streaming where you have the same video encoded into multiple streams using different bitrate.

So which one are you talking about?

**Comment by mkalyon** [comment]
Thank you @frontyard 
I know It is possible on client-side.
But I cannot convince my user.
now I will send your answer.
