### ISSUE TITLE
Play video youtube?

### ISSUE THREAD

**Issue by DavidWilliamBalbino** [frontyard/cordova-plugin-exoplayer#33]
How do I play youtube video?

**Comment by frontyard** [comment]
Just like any other video. But you need a real video url that will return an mpd (DASH),  like this one: 

http://www.youtube.com/api/manifest/dash/id/bf5bb2419360daf1/source/youtube?as=fmp4_audio_clear,fmp4_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=51AF5F39AB0CEC3E5497CD9C900EBFEAECCCB5C7.8506521BFC350652163895D4C26DEE124209AA9E&key=ik0

Google "exoplayer youtube".
