### ISSUE TITLE
Hide player during playback

### ISSUE THREAD

**Issue by shipko** [frontyard/cordova-plugin-exoplayer#35]
Hi, frontyard!
It's possible add method "hide" for hiding player (with saving playback)? Similarly, the calling of the "show" method with a parameter audioOnly.

**Comment by frontyard** [comment]
I'm not sure I understand "with saving playback" part? You can `close` the player to remove it from view. `show` already supports audioOnly.

Maybe you can provide a use case, what are you trying to do?

**Comment by shipko** [comment]
Problem solved

**Comment by jfrux** [comment]
It would be cool if we could hide the player without destroying it?
For instance, this would give us the benefit of only showing it when it's actually playing, else show our own custom loading screen...

Unless I'm missing something?
