### ISSUE TITLE
EventListeners interfere with playback framerate

### ISSUE THREAD

**Issue by mike-tempest** [frontyard/cordova-plugin-exoplayer#37]
After lots of debugging, I have discovered the cause of the slow playback of a video. (30fps playing stuttering more like 15fps).

It is caused by the event listeners firing messages to the Web UI component of the plugin. Do we know if there is any way around it? I have been trying to play with different ways, the only way I can get consistent playback is if I comment out the Event Listener overrides.

Is this something anyone else has experienced?

**Comment by frontyard** [comment]
I haven't seen issues with fps on any of the devices I use for testing. Which events do you think are causing issues?

**Comment by mike-tempest** [comment]
I'm using a Android 7.0.1 device and an emulator. It's the onPlayerStateChanged event that is firing around 3000 times, understandably as its a timeline, however I think because it is on the main thread it is also blocking.

Its also a local mp4 file if that helps for debugging.

**Comment by frontyard** [comment]
Is it possible that you're running in a debug mode and logging all those events?

In my app I'm not even handling STATE_CHANGED_EVENT on the Cordova side, I see no impact on performance on several different low-budget android devices. Emulators are a different thing and measure performance on them is not very reliable.

If this is an issue we can add some kind of optional parameter to disable certain events.

**Comment by frontyard** [comment]
I haven't heard anything new on this so I'll close it. Please feel free to reopen if issue persists.
