### ISSUE TITLE
Exoplayer+ ionic

### ISSUE THREAD

**Issue by devcer** [frontyard/cordova-plugin-exoplayer#39]
Hey,
Do you have any working example of this plugin and ionic 3. cannot find any and I'm getting 'Exoplayer' not defined type of errors.

Thanks,
Santosh.

**Comment by devcer** [comment]
I made one using Ionic 3 but the controls doesn't seem to be available when i touch the screen< https://github.com/devcer/ionic3exoplayer >

**Comment by frontyard** [comment]
There was an issue with 'android.hardware.touchscreen' not being reliably reported by the os. I have fixed this in 2.5.3. Let me know if you still observe the issue.
