### ISSUE TITLE
Cannot install this plugin

### ISSUE THREAD

**Issue by devcer** [frontyard/cordova-plugin-exoplayer#40]
I was getting the following error when i was running the ionic 2 example listed here<https://github.com/spyderboy/ionic2Exoplayer> 
![exoplayer](https://user-images.githubusercontent.com/31848968/30809075-1f665c9c-a21e-11e7-9df6-251dd06a47f0.png)

So I tried to remove the plugin and add it once again but getting the below error. may i know how can i fix this?
![exo-error](https://user-images.githubusercontent.com/31848968/30809035-fb258128-a21d-11e7-9b37-2a02c32c571b.png)

$ionic info gives the following output
```

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.5.3

System:

    Android SDK Tools : 26.0.2
    Node              : v8.4.0
    npm               : 5.4.2 
    OS                : Linux 4.10

Misc:

    backend : pro
```

**Comment by bramovic44** [comment]
Hello

how this problem was solved ?

**Comment by frontyard** [comment]
I believe following PR solve this particular issue:
https://github.com/frontyard/cordova-plugin-exoplayer/commit/00c11daec0dfd6cfde38c485eae32cffaa8fbd29#diff-53f390d375398624afe1cfe1125f42bf
