### ISSUE TITLE
MKV video no audio

### ISSUE THREAD

**Issue by skinot** [frontyard/cordova-plugin-exoplayer#43]
I got no audio in one MKV video.
They work fine in mxplayer and VLC.
How can I add codecs, libraries or something to make it work.

Thanks

**Comment by skinot** [comment]
I figure tha I need to force SW decoder in audio, but dont know how to do it.

Please advice

**Comment by frontyard** [comment]
Make sure audio is encoded in one of the codecs Exoplayer supports:
https://google.github.io/ExoPlayer/supported-formats.html
