### ISSUE TITLE
Player can't go back and Displaying a mini player bar 

### ISSUE THREAD

**Issue by Bobin56** [frontyard/cordova-plugin-exoplayer#44]
Hello , 

Thanks for this awesome plugin . I have successfully manage to implement it on Ionic 3 , when you click a song the player comes in full screen mode but i am a bit unsure of how to go back as clicking a back button won't allow me to do that . here is my code . 

  ```
var params = { 
			url:this.song.data.signed_resource,
			userAgent: 'ExoPlayerPlugin',
			aspectRatio: 'FIT_SCREEN', // default is FIT_SCREEN
			hideTimeout:0, // Hide controls after this many milliseconds, default is 5 sec
			seekTo: 0, // Start playback 10 minutes into video specified in milliseconds, default is 0
			skipTime: 0, // Amount of time to use when going forward/backward, default is 1 min
			controller: { // If this object is not present controller will not be visible
          hideProgress: false,
          streamImage:  `${streamImage}`,
          streamTitle: 'my Music',
          hidePosition: false, // If timebar is visible hide current position from it
          hideDuration: false,
				  controlIcons: {}
			}
		}
		this.platform.ready().then(() => {
			  ExoPlayer.show(params);
    });
```
Also , how do i show a mini player bar instead of going to the player full screen mode . Thanks .

**Comment by frontyard** [comment]
Are you only playing audio? If yes there is a setting to not show the player's UI at all.

All keyboard events need to be handled by your cordova/ionic app. In other words when user presses escape (for example) you can close the player.

As a side note, Smart TV platforms like Webos/Tizen have different keycodes for remote control back button.

**Comment by frontyard** [comment]
I'm gonna close this for now, let me know if I can help further.
