### ISSUE TITLE
Close plugin after player closing

### ISSUE THREAD

**Issue by comrat** [frontyard/cordova-plugin-exoplayer#45]
Hello!
After closing the player via 'close' exec call CordovaPlugin is still opened so I can't go back to point from I've started. Maybe it's normal and I just don't get it. If it's not how can I close the plugin after player was closed too.

**Comment by frontyard** [comment]
Just call `show` again.

**Comment by comrat** [comment]
I mean I need to close plugin.
Imagine movies grid, I pick any film, show player, but I can't close it and choose another one, player closed but cordovaplugin is still alive

**Comment by comrat** [comment]
Thank you, but I've tried it allready.
I'll try to provide a simple example.

**Comment by frontyard** [comment]
That's how it works :-) Can you also provide any errors/exceptions you're seeing?

**Comment by frontyard** [comment]
Any update, did you solve the issue?
