### ISSUE TITLE
Exoplayer is not closing

### ISSUE THREAD

**Issue by Wannerron** [frontyard/cordova-plugin-exoplayer#46]
I've added a backbutton eventlistener to close the exoplayer, but it does not close.

Can you help me?

**Comment by frontyard** [comment]
Sure, but not without further info.

What version of plugin are you using? What version of Cordova?
Can you provide some code around that event listener?

**Comment by Wannerron** [comment]
Cordova: 6.5.0
Plugin: 2.5.0 (Version Latest not working in monaca)

document.addEventListener("backbutton", onAppBackbutton, false);

**Comment by frontyard** [comment]
I'd suggest you upgrade to latest release which is 2.5.3. I'm not saying that's gonna solve your issue but it's difficult to debug older versions.
Also, 
- Are you sure that your onAppBackbutton callback gets called?
- Do you see any exceptions in adb log?
- Do you see any Cordova exceptions when debugging app on devices (chrome://inspect)

**Comment by comrat** [comment]
While writing simple examples for issue reproducing I've figure out what was wrong.
It was problems in my JS code (they were just not obvious for me, sorry). Issue can be closed
Excuse me for disturbing

**Comment by frontyard** [comment]
No worries, glad you solved it!
