### ISSUE TITLE
how do to pass flags like FLAG_ALLOW_NON_IDR_KEYFRAMES

### ISSUE THREAD

**Issue by mazarelo** [frontyard/cordova-plugin-exoplayer#48]
Hey, I am building a IPTV player, and For some reason I cant seem to get exoplayer to play .ts or m3u8 files, I read this could fix a few issues: FLAG_ALLOW_NON_IDR_KEYFRAMES, But how do I add this flags via this plugin? Thanks

**Comment by frontyard** [comment]
Any chances you can fix your TS streams?

I'm a bit hesitant to that flag as a default since it does have a side-effect according to https://google.github.io/ExoPlayer/faqs.html

I'm gonna test it a bit first.

**Comment by mazarelo** [comment]
So the thing is the streams are not mine, I am using providers, and none work using this plugin. Is there any email i can send you one TS file url? Maybe that would help.

**Comment by frontyard** [comment]
If you can post the video somewhere I can download it and test.
