### ISSUE TITLE
Playlist adding

### ISSUE THREAD

**Issue by mkalyon** [frontyard/cordova-plugin-exoplayer#5]
Hi,
How can send playlist like that,
{
"url":"url1",
"name":"name1",
"logo":"logo1"
.......
},
{
"url":"url2",
"name":"name2",
"logo":"logo2"
.......
},
......
If not, can u add playlist support.
I can add string array to Player.java and can play next item using KEYCODE_MEDIA_NEXT keycode.
Thanks

**Comment by mkalyon** [comment]
I have fixed sending playlist for my structure.
Now, I will try to add  showing, controlling, selecting playlist when playing.

**Comment by frontyard** [comment]
Would you mind creating a pull request?

**Comment by casic** [comment]
mkalyon  ,  Show us  how you send  playlist to  player .  Did you  show playlist over exo - dialog  ???

**Comment by frontyard** [comment]
@mkalyon, @casic Do you guys mind discussing a bit how that could be done? I'm generally open to these kinds of feature but I'd be worried about adding more UI code to the plugin.

One of the main goals of this project is to keep it as lean as possible. In other words whatever can be delegated to Cordova app should be delegated to Cordova app.

The choice of using Dialog is unfortunate and should be changed, perhaps with Fragment? Do you guys have spare time to take a stab at that? What that would allow us is to keep all of the UI in Cordova and delegate only media playback to ExoPlayer. Acknowledging that single control UI will not work for everyone, it would be nice to be able to control the player 100% from javascript.

**Comment by mkalyon** [comment]
I want to share my changes on your plugin files.
But these changes are for my cordova app. 
I have add following lines on player.java.
after pull request 
                       exoView.showController();
			show();
			int keyaction = event.getAction();
			cnt=config.getCount();
			if (KeyEvent.keyCodeToString(event.getKeyCode()).equals("KEYCODE_DPAD_UP") && keyaction == KeyEvent.ACTION_DOWN )
			{
				pause();
				count=count+1;
				if (count>=cnt)
				{
					count=1;
				}
				Uri mk=config.getUriLink(count);
				String cname=config.getUriName(count);
				setText(cname);
				String logo=config.getUriLogo(count);
				Picasso.with(imageView.getContext())
                    .load(logo)
                    .into(imageView);
				setStream(mk);
				play();
				
				return true;
			}
			else if (KeyEvent.keyCodeToString(event.getKeyCode()).equals("KEYCODE_DPAD_DOWN") && keyaction == KeyEvent.ACTION_DOWN )
			{
				pause();
				count=count-1;
				if (count<=0)
				{
					count=cnt;
				}
				Uri mk=config.getUriLink(count);
				String cname=config.getUriName(count);
				setText(cname);
				String logo=config.getUriLogo(count);
				Picasso.with(imageView.getContext())
                    .load(logo)
                    .into(imageView);
				setStream(mk);
				play();
				
				return true;
			}

return false;
****************************
and send json data adding my playlist to params. Following lines in a javascript loop.
                                        params["name"+value.number]=value.number+"-"+value.title;
					params["url"+value.number]=value.stream_url;
					params["logo"+value.number]=value.logo;

**Comment by frontyard** [comment]
@mkalyon Of course you're free to do that. However every time there is a change to this plugin you'll have issues merging with your changes. The proper way would be to fork the repo, make changes in a generic way (where other folks might benefit from it) and open a pull request.

**Comment by mkalyon** [comment]
Sorry I am new in github. I will try.
Thanks @frontyard for all supports.

**Comment by casic** [comment]
I'm using this plugin to play  tv channels.  I want to use  touch   "swipe left"  and "swipe right"  to change  the  channels  without  exit from player. But   in  JS  callback i recieve   only   action  "Down" ,"MOVE" and "UP"   with one  coordinate.    How to get  swipe  event ?????   And what  is  different  between  DOWN and MOVE.  and  MOVE  and UP ???

**Comment by frontyard** [comment]
@casic I'm reworking some stuff in 2.0.0-DEV branch but master should work the same and just use  different events names/keys.

For touch events ACTION_DOWN is user touching down and eventAxisX and eventAxisY will be the coordinates of that touch. ACTION_UP will be where user lifted the finger and you need those coordinates too. With those 4 numbers you can figure out the distance and the direction of the swipe using simple math.

**Comment by casic** [comment]
I have thinked so. And i have made that by this way.   Most touches  this work fine.  BUT !!!!    When  swipe  begin  with  ACTION_DOWN and  finish with ACTION_UP     all is   ok.     BUT some times  ,  swipe begin with ACTION_DOWN and finish with ACTION_MOVE  ?????  Some time swipe  begin with  ACTION_MOVE  and finish with ACTION_UP.    In this  cases ,  nothing works.

**Comment by casic** [comment]
@frontyard   Great work. Very usefull plugin for me. Thanks for sharing. I have looked for something like that. I just  replaced onView.setTouchListener  and now i  have great app.  Thanks again.
