### ISSUE TITLE
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebug'.

### ISSUE THREAD

**Issue by a930334** [frontyard/cordova-plugin-exoplayer#50]
Hi,

When i build my app after install this plugin, I get this error:

-------------------------------------------------------------------------------------------------------------------------
(...)
:compileDebugSources
:transformClassesWithDexBuilderForDebug

:transformDexArchiveWithExternalLibsDexMergerForDebug
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
39 actionable tasks: 37 executed, 2 up-to-date
(node:21038) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: /home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

(...)
-----------------------------------------------------------------------------------------------------------------------------

That's what i get when I run "ionic info"

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 browser 5.0.3 ios 4.5.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v6.12.3
    npm               : 3.10.10 
    OS                : Linux 4.14

Environment Variables:

    ANDROID_HOME : /home/jcarlos/Android/Sdk

Misc:

    backend : legacy

Regards

**Comment by frontyard** [comment]
This looks like it has nothing to do with the plugin.

**Comment by a930334** [comment]
When I try to build the app whithout this plugin, i have no problem...
