### ISSUE TITLE
How to add a back button

### ISSUE THREAD

**Issue by fadeli1** [frontyard/cordova-plugin-exoplayer#53]
In the video player interface, how to add a return button to return to the previous page, thank you

**Comment by fadeli1** [comment]
![Uploading 2.png…]()

**Comment by fadeli1** [comment]
![2](https://user-images.githubusercontent.com/1914030/36823473-4ab5219a-1d38-11e8-8cb8-07558a33ca22.png)

**Comment by mkalyon** [comment]
Why do you need back button?
You can use BACK button of device and you can control KEY_EVENT in successCallback  function.

Please read README.md
Example of key events:

{
    'eventType':'KEY_EVENT',
    'eventAction':'ACTION_DOWN',
    'eventKeycode':'KEYCODE_VOLUME_UP'
}

{   
    'eventType':'KEY_EVENT',
    'eventAction':'ACTION_UP',
    'eventKeycode':'KEYCODE_VOLUME_UP'
}

**Comment by fadeli1** [comment]
OK, I'll try
