### ISSUE TITLE
Build error for 2.5.4

### ISSUE THREAD

**Issue by mkalyon** [frontyard/cordova-plugin-exoplayer#56]
Hi,
I have got error while building.
I use cordova exoplayer plugin version 2.5.4.
Cordova 8.0.0  / Android platform 7.0.0

Error is:
***********************************
cp: copyFileSync: could not write to dest file (code=ENOENT):C:\cordova7\app\exo1\platforms\android\res\xml\config.xml

Parsing C:\cordova7\app\exo1\platforms\android\res\xml\config.xml failed
(node:3596) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'C:\cordova7\app\exo1\platforms\android\res\xml\config.xml'

**************************************

Note that there is no problem for old versions.

**Comment by frontyard** [comment]
You can't use Android platform 7.0.0 just yet, use ~6.2.3 for now.

Cordova made a giant mess moving files around in version >7.0.0. A lot of plugins don't work with it yet.

**Comment by mkalyon** [comment]
Thanks Nedim.

**Comment by hitaloramon** [comment]
I'm having trouble with version 2.5.4 as well.
I'm using android platform 6.2.3

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.android.support:support-annotations:27.0.0.
     Searched in the following locations:
         file:/C:/Users/hital/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
         file:/C:/Users/hital/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
         file:/E:/projetos/App/platforms/android/sdk-manager/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
     Required by:
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-core:2.6.1
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-dash:2.6.1
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-hls:2.6.1
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-smoothstreaming:2.6.1
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-ui:2.6.1

* Try:
Run with --stacktrace option to get the stack trace. Run with
BUILD FAILED

Total time: 4.042 secs
--info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.android.support:support-annotations:27.0.0.
     Searched in the following locations:
         file:/C:/Users/hital/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
         file:/C:/Users/hital/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
         file:/E:/projetos/App/platforms/android/sdk-manager/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
     Required by:
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-core:2.6.1
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-dash:2.6.1
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-hls:2.6.1
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-smoothstreaming:2.6.1
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-ui:2.6.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by hitaloramon** [comment]
I am trying the following error to install version 2.5.4:
Any solution? I'm using the android platform 6.2.3


Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.android.support:support-annotations:27.0.0.
     Searched in the following locations:
         file:/C:/Users/hital/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom
         file:/C:/Users/hital/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
         file:/E:/projetos/teste/platforms/android/sdk-manager/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
     Required by:
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-core:2.6.1
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-dash:2.6.1
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-hls:2.6.1
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-smoothstreaming:2.6.1
         project : > com.google.android.exoplayer:exoplayer:2.6.1 > com.google.android.exoplayer:exoplayer-ui:2.6.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by frontyard** [comment]
support-annotations is a dependency of ExoPlayer. Not sure why you're having this issue but I would recommend cleaning everything. Are you sure you're not using Cordova 7?

**Comment by hitaloramon** [comment]
![image](https://user-images.githubusercontent.com/12436779/39454730-5f66172a-4cb3-11e8-9458-7ae40b85dc7f.png)

**Comment by lello1978** [comment]
I have the same issue with cordova 7.1.
I want to contribut but java isn't so familiar for me. If you need further infos, i can produce logging.

**Comment by frontyard** [comment]
@lello1978  Version of cordova is not relevant. Version of cordova-android is crucial. This plugin doesn't work with cordova-android 7 and above. Cordova has changed location of files within platforms/android and bunch of plugins (including this one) still use the old layout.

**Comment by lello1978** [comment]
Thank for the info....
The only plugin fork who i'm able to include in my project is https://github.com/vinogradov-m/cordova-plugin-exoplayer
The developer have changed the name, and called it "Lite".
I'm not able with my poor Java knowledge to find the real issue or to revert to a compatible status.
I hope this discussion can help someone.

In the next day i'll prepare a Java dev environment to start to improve this plugin...

**Comment by frontyard** [comment]
Can you try the following:

In your project's "platforms/android" create a new file called build-extras.gradle

In that file add the following:
`allprojects {
    repositories {
        maven { url 'https://maven.google.com' }
    }
}

configurations.all {
  resolutionStrategy.eachDependency { DependencyResolveDetails details ->
    // Pin the support library version so that all libraries use the same one
      if (details.getRequested().getGroup() == 'com.android.support') {
        details.useVersion('25.0.1')
      }
    }
}
`

After that build your app but make sure "platforms/android" directory is not deleted in the process.

If that works you can create a Cordova hook for "before_build" stage that copies this file from somewhere safe into platforms/android.

**Comment by lello1978** [comment]
Thank for all suggestions. Now we are using a platform named WaveMaker to build apps for mobile. We compose the app and add plugins with webbrowser only. The backend builder is phonegap. I do not know how to integrate your changes into our platforms. I'll proceed with two ways: (1) I ask to platform maintainer and (2) try to find the difference between the plugin that work and your plugin that doesn't work.
Do you have other suggestion?

**Comment by lello1978** [comment]
I forked the project. With your suggestion the build process end correctly on phonegap. Today i'm goind to test the plugin inside javascript.

**Comment by frontyard** [comment]
I'm not sure what WaveMaker is but if it's based on PhoneGap/Cordova you should be ok. Let me know.

**Comment by lello1978** [comment]
Ok i try to use the version 2.5.4 after the successful build. The app crash and restart instantly.
I don't know hoe to debug it. Sorry. I try to reveert to version 2.5.3. How can i help you to debug the app?

**Comment by frontyard** [comment]
First thing to do is connect to the device you're using for debugging via USB cable and on the command prompt run:
```
adb logcat
```
You should be seeing a lot of stuff coming from android. Start the app on the device and watch the logs. When you app crashes stop the log, go back and look for any exceptions related to your app.

Another thing to do for PhoneGap/Cordova apps is build them in debug mode, install them through adb and run them (having Android device attached via USB) Then open Chrome and in the address field type:
```
chrome://inspect
```
You should see your app and should be able to click on it and see what's going on.

**Comment by lello1978** [comment]
I'll give you some feeback in the next days...i need to prepare also the dev env...sorry

**Comment by khalisafkari** [comment]
please add support for vast ads
