### ISSUE TITLE
The event KEYCODE_BACK in android 7.1 force app go in backgroun

### ISSUE THREAD

**Issue by lello1978** [frontyard/cordova-plugin-exoplayer#58]
When i press back  button in android 8, the app fires the right events and app go back to the page that 
launched the video....In android 7 the app ween in background.    
I suppose that is not the intended behaviors.

What do you suggest. If you need others info....i want to help!
Regards

Player Success callback fired (playerSuccessCallback) {eventType: "KEY_EVENT", eventAction: "ACTION_DOWN", eventKeycode: "KEYCODE_BACK"}
app.js:89 
Player Success callback fired (playerSuccessCallback) {eventType: "STOP_EVENT"}

**Comment by frontyard** [comment]
When you press back button the plugin will fire KEYCODE_BACK. You can then do ExoPlayer.close() to get rid of the player which should land you back to the screen that started the player. This shouldn't behave any differently between Android 7 and 8.

On some devices pressing home button will send you to the launcher while the app might still be running in the background. To handle this you should use these 2 Cordova events:
```
document.addEventListener('pause', pauseEventHandler, false);
document.addEventListener('resume', resumeEventHandler, false);
```
And at the very minimum stop the playback in pauseEventHandler.
