### ISSUE TITLE
place subtitles in VTT or SRT?

### ISSUE THREAD

**Issue by rafagouveia** [frontyard/cordova-plugin-exoplayer#6]
Hi, i can place subtitles in **VTT** or **SRT**?

I did not see anything about it.

**Comment by hitaloramon** [comment]
Hi, @frontyard 
Would it be possible to add an option to pass a URL to a caption in **vtt** or **srt**?

Sorry for my english, I used google translate

**Comment by frontyard** [comment]
@rafagouveia @hitaloramon Let me take a look at what it would take.

**Comment by frontyard** [comment]
I've looked into this a bit. Google's documentation of ExoPlayer is not very good, but I believe we can make this happen. It just might take few days.

**Comment by frontyard** [comment]
@rafagouveia, @hitaloramon Version 2.1.0 now has support for subtitles. Make sure to check the updated [main page](https://github.com/frontyard/cordova-plugin-exoplayer)

**Comment by rafagouveia** [comment]
Oh right, thanks for support, e your fast response!

**Comment by hitaloramon** [comment]
Thanks for the quick support. I tested the previous version worked normally, this new could not initialize. I saw that in the example parameters there are two commas missing in:

`AspectRatio: 'FILL_SCREEN' and audioOnly: true
`
I added the commas and it still did not work. I looked at the error console and did not display any messages.

**Comment by frontyard** [comment]
@hitaloramon I will fix the documentation but that's not affecting the player. Please try to debug both Cordova and Android.
For Android, run adb logcat from the command line.
For Cordova, with your device attached to USB open Chrome, type chrome://inspect and attach to your app.

**Comment by hitaloramon** [comment]
Thank you @frontyard. Get it now. Worked perfectly. Would it be possible to add a button to enable and disable the caption in the player?

**Comment by frontyard** [comment]
@hitaloramon Looks like we've solved the fullscreen issue.

As for the button for the subtitles, like with anything related to the UI, the main issue is keeping 100% support for both touchscreen and keyboard (remote). That is not trivial and takes time to figure and get it right. And this time I'm not sure I have enough time but I'll open a new feature ticket if anyone is interested in taking a stab at it.
