### ISSUE TITLE
Unable to build with cordova android 7.1.0

### ISSUE THREAD

**Issue by acollazomayer** [frontyard/cordova-plugin-exoplayer#63]
After i install the plugin i am unable to build the app i get this error:

cp: copyFileSync: could not write to dest file (code=ENOENT):/home/agustin/Projects/compilations/exoplayer/platforms/android/res/xml/config.xml

**Comment by frontyard** [comment]
See https://github.com/frontyard/cordova-plugin-exoplayer/issues/56

**Comment by acollazomayer** [comment]
ok perfect, i just downgrade the android-cordova version to 6.4.0.

**Comment by acollazomayer** [comment]
@frontyard I have another question. Does this works with HTTPS video files, the player throws me an error of a "Trust anchor for certification path not found

**Comment by frontyard** [comment]
It should. The plug-in really doesn't do anything to urls, just sends them to ExoPlayer, so whatever Exo supports plug-in supports too.
