### ISSUE TITLE
2.5.4 showbuffering false not working

### ISSUE THREAD

**Issue by acollazomayer** [frontyard/cordova-plugin-exoplayer#64]
in the version 2.5.4 showbuffering false is not working

**Comment by neo725** [comment]
i'm also have this problem too,
so i just doing a quick try to fix this problem and create a pull-request https://github.com/frontyard/cordova-plugin-exoplayer/pull/66

my way is:

in Player.java line:238
the code should be this :
```
LayoutProvider.setupController(exoView, activity, config.getController());
```
insert this code below:
```
if (!config.getShowBuffering()) {
    LayoutProvider.setBufferingVisibility(exoView, activity, false);
}
```

if you accept my fix, then you can wait till owner merge my pr.
or you can fix by yourself.

**Comment by vineshhpatel** [comment]
I had the same issue and was able to hack it by setting alpha to '00' for bufferingColor
you can set `bufferingColor: '#00dddddd'` to hide buffering.

**Comment by frontyard** [comment]
If you have a fix please submit a pull request.
