### ISSUE TITLE
Add package.json file (and ideally upload to npm)

### ISSUE THREAD

**Issue by netmikey** [frontyard/cordova-plugin-exoplayer#7]
Installing the plugin on the latest Cordova version with the instructions in the `README.md` brings up the following error:

```
$ ../node_modules/.bin/cordova plugin add https://github.com/frontyard/cordova-plugin-exoplayer
Error: Failed to fetch plugin https://github.com/frontyard/cordova-plugin-exoplayer via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 235 Error output:
npm ERR! addLocal Could not install /var/folders/yq/t6hfv8453z5693m7zt4m0qsh0000gn/T/npm-5152-64b122ae/git-cache-65041863/eb052c879ecfc600ddd09510c72f491a821a5fb7
npm ERR! Darwin 16.5.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install" "https://github.com/frontyard/cordova-plugin-exoplayer" "--save"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.8
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.
```

Forgive me if I'm getting it wrong, I'm totally new to Cordova, but as far as I understand, this comes from the following change:

> As far as I understand, the problem is that fetch is now used by default. [...]
> With fetch, plugins now need a package.json since cordova-fetch will npm install the plugin.

https://issues.apache.org/jira/browse/CB-12680
https://issues.apache.org/jira/browse/CB-12685

Finally, it would be very helpful for app developers it you'd provide the plugin via npm :-)

**Comment by frontyard** [comment]
@netmikey I'll update the project with package.json and release it to npm.

**Comment by frontyard** [comment]
@netmikey Version 2.0.1 is in npm now! BTW, this is a brand new version with lots of minor changes (hence the version bump). Please let me know if it works for you.

**Comment by netmikey** [comment]
@frontyard Awesome, the plugin is working perfectly now! :)

A quick question: I'm trying to stream audio only. Is it possible to have the player be running completely headless (e.g. no GUI element at all, just play in the background)?

Thanks again for the quick support! :)

**Comment by frontyard** [comment]
@netmikey Version 2.1.0 now has audioOnly: true. Make sure to check the updated [main page](https://github.com/frontyard/cordova-plugin-exoplayer)

**Comment by netmikey** [comment]
@frontyard Awesome, thanks a lot!! 👍
