### ISSUE TITLE
Video still playing on background

### ISSUE THREAD

**Issue by RhuanGonzaga** [frontyard/cordova-plugin-exoplayer#70]
Hi, I'm using ionic on my project and when user press home or app switch buttons of android the video streaming still playing, I would like pause video when user is not seeing that activity, is it possible ?

Ionic info:

Ionic:

   ionic (Ionic CLI) : 4.2.1 (C:\Users\1513 IRON\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.7

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, (and 8 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Android\sdk)
   NodeJS            : v8.11.1 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10

Thanks!

**Comment by frontyard** [comment]
When your press home button your app will receive 'pause' Cordova event. You can then pause or stop the playback.
When your app becomes focused again it will receive 'resume' Cordova event.
`
  document.addEventListener('pause', pauseEventHandler, false);
  document.addEventListener('resume', resumeEventHandler, false);
`
