### ISSUE TITLE
Build error for cordova android 6.4.0

### ISSUE THREAD

**Issue by hldevup** [frontyard/cordova-plugin-exoplayer#73]
Hello,
im getting this error when i try to build my app
`:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:javaPreCompileDebug UP-TO-DATE
C:\Users\HDSTL\Desktop\Projects\ionNetflix\platforms\android\src\co\frontyard\cordova\plugin\exoplayer\Player.java:72: error: <anonymous co.frontyard.cordova.plugin.exoplayer.Player$1> is not abstract and does not override abstract method onTimelineChanged(Timeline,Object,int) in EventListener
    private ExoPlayer.EventListener playerEventListener = new ExoPlayer.EventListener() {
                                                                                        ^
C:\Users\HDSTL\Desktop\Projects\ionNetflix\platforms\android\src\co\frontyard\cordova\plugin\exoplayer\Player.java:118: error: method does not override or implement a method from a supertype
        @Override
        ^`
Any help pls

**Comment by frontyard** [comment]
Did you get this working? Are you using branch 2.0.0?

It looks like wrong version of exoplayer library is somehow being pulled in.

**Comment by RhuanGonzaga** [comment]
Same error here, tried to use branch 2.5.4 and 2.5.5 any works.
