### ISSUE TITLE
Cordova Overlay

### ISSUE THREAD

**Issue by CanJr** [frontyard/cordova-plugin-exoplayer#74]
I have a problem. As soon as I start the stream, my html gui will be covered. But it should be the other way around. Can someone help me ? I need this sooooooo badly

**Comment by frontyard** [comment]
If you're looking for help you should provide more details.

If I understand you correctly, your app works exactly as it should, when you start the stream, Cordova UI is hidden and stream becomes visible.

**Comment by CanJr** [comment]
I have created a user interface with HTML. In the HTML is a list of links. When I click on a link, this link should open in the stream and close the user interface.  This also works as it should, but if I now click in the middle of the DPad, my HTML should be above the stream. But that doesn't happen. The stream is always in the foreground. But I don't want that. So I want to go up and down the list of my html. As you know it in tv software.

**Comment by frontyard** [comment]
Whether something should or should not happen is up for a debate ;-)

It sounds like you're not handling those clicks properly. What you need is keyboard events handler in your Cordova app for remote control. Then dpad nav keys can move your "focused" element and select/ok can start the stream.

Also this plugin doesn't "close" your user interface, that's not it's job. It just opens a new container for the streamed video.

**Comment by CanJr** [comment]
and how can i put the container in the background and my user interface in front of the stream ? Can I do that with css? if so, what is the name of the css class for the stream ?

**Comment by frontyard** [comment]
You can't put container in the background. What you do is close it. Check the [README](https://github.com/frontyard/cordova-plugin-exoplayer/blob/2.0.0/README.md).

**Comment by frontyard** [comment]
You can't do that. It's currently not possible to position player's Dialog in the background of Cordova's webview.

**Comment by CanJr** [comment]
Okay. Maybe you'll have another solution? I really need it.

**Comment by forumrulez** [comment]
> You can't do that. It's currently not possible to position player's Dialog in the background of Cordova's webview.

It would be very cool if you could add elements on top of the player yourself, maybe you can give some example how to add for example an input field in .java indicating the position x \ y? As a small example

**Comment by frontyard** [comment]
All of that is just standard Android development. Take a look at layout folder for example.

If you want to play with it, you will need to set up for Android development, clone this repo and try changing some stuff. You can symlink or npm link your cloned plugin when you build your app.

**Comment by casic** [comment]
I also have to make  LIST with streams  transparent over video.   I have just  opened plugin  and make  Android ListView ,   android OnView.Listener  , touches , swipes  and so on.

**Comment by frontyard** [comment]
A bit of personal opinion ... there's a reason we're using Cordova for our apps. Cross-platform, easy and fast development, possibility of live updates etc. If you can avoid doing things natively you will be much happier long term. But sometimes, it's unavoidable. It's also outside of the scope of this plugin, so you'll have to figure it out yourself :-)

**Comment by casic** [comment]
You are right of course.  I just looked for  other way , only with JavaScript  , but not found.  I have read all about this  overlay with webView , and realize , there is no way.  I'm not  Java developer , but the NEED  help me to write it. Now  worked fine.

**Comment by mkalyon** [comment]
Hi
Open google then search 
cordova listview plugin 
This solves your listing problem.

**Comment by sabado** [comment]
I think the cordova web view overlay is a really powerfull ideal to implement. You just in minutes can play background videos, create galleries like youtube, etc just using html, and the powerfull of native playback. I can donate some for that, any voluntaries?

**Comment by Nemanja02** [comment]
Has anyone managed to play video behind transparent cordova?

**Comment by frontyard** [comment]
There is some new development that might give you what you need which is using Cordova to do player controls vs controls built into this plugin. This would really be the ideal solution, if it works :-)

Check the latest code in 2.0.0 branch.
