### ISSUE TITLE
How to  View 360 degree video 

### ISSUE THREAD

**Issue by jaber9030** [frontyard/cordova-plugin-exoplayer#75]
i saw in this article that Exo player became support 360-degree videos  in version  2.9 https://medium.com/google-exoplayer/playing-360-degree-videos-with-exoplayer-f3b48f8ea390 
so does it available in ionic cordova library?

**Comment by frontyard** [comment]
It would require upgrading exoplayer library which would require code changes to the plugin and extensive testing. I suggest forking, making changes and creating a pull request.
