### ISSUE TITLE
how to change streamTitle during stream is still in played

### ISSUE THREAD

**Issue by vista136** [frontyard/cordova-plugin-exoplayer#78]
i use controller param like this 

controller: { // If this object is not present controller will not be visible
        streamTitle: "ex 1",
        streamDescription: "desk ex 1",
 }

when I try to show up the controller is right like that

but how to change the streamTitle and streamDescription during stream is still in played

and i want to ask,, how to use  -->  setController() <-- 

I have tried with the following options

1.    window.ExoPlayer.setController();   <-- nothing happen in my app

2. var control = {
          streamTitle: "ex 2",
          streamDescription: "desk ex 2",
    }
  window.ExoPlayer.setController(control ); <--  same.., nothing happen in my app

3. var control = {
         controller {
             streamTitle: "ex 2",
             streamDescription: "desk ex 2",
         }
    }
  window.ExoPlayer.setController(control) <--  my app is exit like crash

**Comment by frontyard** [comment]
Try adding:
window.ExoPlayer.showController();
AFTER setController call.

**Comment by vista136** [comment]
how to use it correctly?
can you give 1 full example of how to use it
