### ISSUE TITLE
Controlling the player volume

### ISSUE THREAD

**Issue by netmikey** [frontyard/cordova-plugin-exoplayer#8]
Would it be possible to add the ability to set the player volume?
This is useful for setting a preferred initial volume as well as having a possibility to control the volume when `audioOnly: true` is set.

Maybe something like:

    setVolume(number)   // A number between 1 and 100, or a decimal between 0 and 1.

Maybe also add an optional parameter to the `init(params)` call?

**Comment by frontyard** [comment]
@netmikey I have another plugin that might be helpful: [cordova-plugin-android-utilities](https://github.com/frontyard/cordova-plugin-android-utilities)

**Comment by netmikey** [comment]
You're right, looks like there are enough plugins to handle volume control already.
