### ISSUE TITLE
Update to API 28

### ISSUE THREAD

**Issue by preterive** [frontyard/cordova-plugin-exoplayer#80]
Please make the Plugin working with API 28.
There is a update needed till november 2019
https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by preterive** [comment]
There is simple no Support for http anymore, only https.

**Comment by frontyard** [comment]
The way to specify target API is through config.xml:
```xml
<platform name="android">
      ...
        <preference name="android-minSdkVersion" value="17"/>
        <preference name="android-targetSdkVersion" value="28"/>
        <preference name="android-compileSdkVersion" value="28"/>
```
