### ISSUE TITLE
Is version 2.5.4 working on  cordova android 8 ?

### ISSUE THREAD

**Issue by samsoft08** [frontyard/cordova-plugin-exoplayer#83]
I'm trying to run the plugin on cordova android 8 , but I'm facing many issues..
is it possible to do it ?

**Comment by mkalyon** [comment]
Hi friends,
I have added exoplayer 2.11.3 to cordova android 8.1.0.
New features
-showtoast
-show/select video/audio/subtitle tracks
- clock
And etc...
I will share it when complete new plugin.
There are some issues. But I can solve them with adding manuel properties.
Thanks @frontyard for this plugin.

**Comment by samsoft08** [comment]
can this player controlled by android TV box remote control ?

**Comment by mkalyon** [comment]
> can this player controlled by android TV box remote control ?

This question is not about your issue title.
Please read readme file , you can find annswer succescallback function.

**Comment by samsoft08** [comment]
thanks

**Comment by frontyard** [comment]
@mkalyon Any chance you can submit a pull request with your changes?

**Comment by mkalyon** [comment]
> @mkalyon Any chance you can submit a pull request with your changes?

I dont complete it yet. If you want , I can send it with my changes.. But I dont know how to share it only with you in github.

**Comment by mkalyon** [comment]
> 
> 
> > @mkalyon Any chance you can submit a pull request with your changes?
> 
> I dont complete it yet. If you want , I can send it with my changes.. But I dont know how to share it only with you in github.

Ok I can find it. I wil share it for only you

**Comment by mkalyon** [comment]
@frontyard I have added you, you can see it.

**Comment by jacksun101** [comment]
@mkalyon Any update on this? I am working on a cordova project and need this. Or maybe I can help with some guidances.

**Comment by mkalyon** [comment]
> @mkalyon Any update on this? I am working on a cordova project and need this. Or maybe I can help with some guidances.

Hi
It is ready for usage. Now my users test it.
I will share new plugin with new features.

**Comment by jacksun101** [comment]
@mkalyon I'm glad to hear this good news. Is there release schedule that I can be looking forward to trying the new plugin? Does it support DRM video download and play-offline?

**Comment by itziks00** [comment]
Great...
I tired to use the current plugin and made changes, I managed to play something but after few minutes the app crashes with exception.

I'm waiting too :)

**Comment by frontyard** [comment]
@itziks00 if you post your exception people might be able to help. This plugin has been running in production for years without any issues, so I'm gonna guess it's your app.

**Comment by rcasunshare** [comment]
Why is there no update for this plugin? The latest version of ExoPlayer 2.11.7

**Comment by frontyard** [comment]
Mainly because for the author of this plugin (yours truly) it's working and it's is stable. It will have to happen at some point and will most likely involve upgrading of cordova as well which breaks existing projects in major ways and requires significant amount of development and testing.

**Comment by frontyard** [comment]
Having said that, any pull requests that solve issues for people (including upgrades to underlaying frameworks) are more than welcome.

**Comment by rcasunshare** [comment]
> Having said that, any pull requests that solve issues for people (including upgrades to underlaying frameworks) are more than welcome.

Does this plugin work with the latest version ExoPlayer 2.11.7? If it does not work then this plugin is obsolete.

**Comment by frontyard** [comment]
lol no it's not obsolete, how did you figure that out? Projects are rarely on last versions of their dependencies. Upgrading dependencies 1) takes time and effort and 2) you need a good reason for doing so.

So what in 2.11.7 is essential for this project to move to it? And if you really really need it, do an upgrade and submit a pull request. This is an open source project that depends on people volunteering their time to work on it.

**Comment by mkalyon** [comment]
This plugin is already used in a lot of applications.
It is not absolute.
Thank you again @frontyard for this plugin and your time.

**Comment by mkalyon** [comment]
Hi,
mkExoPlayer plugin ready for test with ExoPlayer 2.11.8
https://github.com/mkalyon/cordova-plugin-mkExoplayer

Please read README.md for usage
