### ISSUE TITLE
PlayPause not working

### ISSUE THREAD

**Issue by Geowan** [frontyard/cordova-plugin-exoplayer#85]
AM listening to key events and executing the playpause but doesnt seem to play or pause.

I have added the following.

         var params = {
          url: url,
          audioOnly: false,
          showBuffering: false, // When buffering, player will show indicator at the top of the screen, default is false
           controller: { // If this object is not present controller will not be visible
            controlIcons: {},
            hideProgress: false, // Hide entire progress timebar
            hidePosition: false, // If timebar is visible hide current position from it
            hideDuration: false, // If timebar is visible Hide stream duration from it
            textColor: '#dddddd', // These colors can be any valid Android color
            buttonsColor: '#00ff001C', // This example uses hex values including alpha (first byte)
            bufferingColor: '#00dddddd' // Alpha of 'ff' makes it 100% opaque
          }
        };
         window.ExoPlayer.show(params, function (event) {

           if (event.eventType === "KEY_EVENT" && event.eventKeycode === "KEYCODE_Q") {
             window.ExoPlayer.playPause();
            console.log("key clicked"); //this is called twice
          }
      }

Whenever i click on the q it briefly pauses and then plays the video once more. It doesn't fully stop playing the video.
I have also checked on the console which happens twice. Why is this so?
 
How can i resolve this issue as from the readme i can see playPause is supposed to pause the video then play it when the key is clicked again.

**Comment by frontyard** [comment]
Are you listening for keyboard events on keydown or on keyup?
