### ISSUE TITLE
update ExoPlayer to 2.11.7

### ISSUE THREAD

**Issue by rcasunshare** [frontyard/cordova-plugin-exoplayer#88]
Please update ExoPlayer to 2.11.7 Urgent!!!

**Comment by mkalyon** [comment]
I will publish mkExoplayer plugin(used and updated @frontyard  exoplayer plugin) in September.

Used

-- Exoplayer v2.11.7
-- Cordova 8.0.0
-- Android Platform 8.1.0

New Features:
-Sending Playlist
-Selection Subtitle/Audio tracks (if media has them)
-Loading spinner
-Epg data line
-Description line
-keyEvent control
-timeZone parameter for clock
-Clock
-Toast message
-Added getSubtitles / getAudios / getVideos / getPlaylist / showToast / createList

**Comment by mkalyon** [comment]
Hi,
mkExoPlayer plugin ready for test with ExoPlayer 2.11.8
https://github.com/mkalyon/cordova-plugin-mkExoplayer

Please read README.md for usage

Thanks @frontyard
