### ISSUE TITLE
Missing packages from android build when using this plugin

### ISSUE THREAD

**Issue by ashutoshsingh0223** [frontyard/cordova-plugin-exoplayer#90]
When I install 2.5.4 version of this plugin. I am on an ionic-react app.  So I used capacitor to install this plugin.

I am facing number of problems when I try to build my apk after building the app.

I basically get a lot of missing package errors. When I try to add these packages manually and do a gradle sync I still get the errors.

Adding a picture for the list of missing packages. Everything is red is missing. ui package was also missing. I manually added it to gradle.

Environment Information:
```
ext {
    minSdkVersion = 21
    compileSdkVersion = 29
    targetSdkVersion = 29
    androidxAppCompatVersion = '1.1.0'
    androidxCoreVersion =  '1.2.0'
    androidxMaterialVersion =  '1.1.0-rc02'
    androidxBrowserVersion =  '1.2.0'
    androidxLocalbroadcastmanagerVersion =  '1.0.0'
    firebaseMessagingVersion =  '20.1.2'
    playServicesLocationVersion =  '17.0.0'
    junitVersion =  '4.12'
    androidxJunitVersion =  '1.1.1'
    androidxEspressoCoreVersion =  '3.2.0'
    cordovaAndroidVersion =  '7.0.0'
}
```

![issues](https://user-images.githubusercontent.com/40604544/91664207-8bd7d200-eaa2-11ea-943c-2f29457ef9a0.png)

**Comment by ashutoshsingh0223** [comment]
@frontyard We are trying to go live with something. And we have tried everything for example sing older versions of your plugin etc. We would be very grateful if you guide us through this.

**Comment by frontyard** [comment]
@ashutoshsingh0223 I personally use Cordova not Ionic and plain JS not React. I use a simple shell script to build packages for various targets, there's no "magic" involved. The fact that your Webstorm can't find those packages doesn't mean much, as Westorm project setup has nothing to do with how you build a project (Webstorm and your build tool of choice have different ways to resolve dependencies). Sorry, maybe ask on some Ionic support channel? I know people are using this plugin with Ionic successfully.

**Comment by ashutoshsingh0223** [comment]
Okay thanks

**Comment by hieloverde** [comment]
I´m facing the same issue with version 2.5.4 of this plugin. Cordova android 9, Gradle 6.8.3 (also tried gradle 6.1.1 with same result).

**Comment by apetrichkovich** [comment]
Hello.
I've created new project:
cordova create hello com.example.helloapp Hello
cd hello
cordova plugin add cordova-plugin-exoplayer
cordova platform add android

And code is not up to date:
SimpleExoPlayerView is not found (renamed to PlayerView);
PlaybackControlView is not found;
ExoPlayerFactory is not found;
DashMediaSource.DEFAULT_LIVE_PRESENTATION_DELAY_PREFER_MANIFEST_MS is not found;
ExtractorMediaSource is not found;
and few things in co.frontyard.cordova.plugin.exoplayer.Player

Please, can you fix it?

**Comment by hieloverde** [comment]
This one worked for me https://github.com/mkalyon/cordova-plugin-mkExoplayer
