### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by halibegic** [frontyard/cordova-plugin-exoplayer#95]
Build failed with an exception.

```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer:2.9.6.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer/2.9.6/exoplayer-2.9.6.pom
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer/2.9.6/exoplayer-2.9.6.pom
     Required by:
         project :app
```

**Comment by frontyard** [comment]
Version of exoplayer has been upgraded to 2.9.6 recently to help with upgrade to the latest android and cordova versions. This version of the plugin works with:
cordova: 11.0.0 (latest)
cordova-android: 9.1.0
exoplayer: 2.9.6 

If you are having trouble resolving exoplayer try putting this in your build-extras.gradle and making sure this file is in platform/android before you build your app.

```
allprojects {
    repositories {
        maven { url 'https://maven.google.com' }
    }
}
```

If you are not able to upgrade your exoplayer you can stay on version 2.5.5 of this plugin.

**Comment by kd8ssq** [comment]
This error shows up when using cordova-android 10.1.2.  I've tried plugin versions 2.5.4-2.5.6 and you still get the same error.

Using cordova-plugin-exoplayer version 2.5.6 and downgrading to cordova-android to 9.1.0 does seem to let the build process, but that's several android versions behind.

Also, @frontyard, it looks like the version number hasn't been updated in the plugin.xml file.  Still shows 2.5.4.

**Comment by frontyard** [comment]
For posterity, install the plugin from git not npm. If I get some time I'll release latest version to npm but there are no guarantees.
